# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp'),
        ),
        migrations.AddField(
            model_name='post',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Update Timestamp'),
        ),
    ]
