# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170224_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.Block', verbose_name='Block Name'),
        ),
    ]
