# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170302_1620'),
        ('posts', '0003_auto_20170224_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='Author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=10000, verbose_name='Content'),
        ),
    ]
