# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.CharField(blank=True, max_length=300, verbose_name='Picture'),
        ),
    ]
