# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.CharField(blank=True, max_length=30000, verbose_name='Picture'),
        ),
    ]
