# Generated by Django 2.1 on 2018-04-26 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_post_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.User', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blocks.Block', verbose_name='Block Name'),
        ),
    ]
