# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0013_auto_20170413_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000, verbose_name='Content')),
                ('link', models.CharField(max_length=10000, verbose_name='Link')),
                ('status', models.IntegerField(choices=[(1, 'Unread'), (0, 'Read')], default=1, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='User id')),
            ],
        ),
    ]
