# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='post_title',
            field=models.CharField(default='', max_length=1000, verbose_name='Post Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='replyer',
            field=models.CharField(default='', max_length=100, verbose_name='Replyer'),
            preserve_default=False,
        ),
    ]
