# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20170413_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='create_date',
            field=models.CharField(auto_created='2017-04-14', default='', max_length=50, verbose_name='Create date'),
            preserve_default=False,
        ),
    ]
