# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_message_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_date',
            field=models.CharField(auto_created='2017-04-29', max_length=50, verbose_name='Create date'),
        ),
    ]
