# Generated by Django 2.1 on 2018-04-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20180426_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_date',
            field=models.CharField(auto_created='2018-04-29', max_length=50, verbose_name='Create date'),
        ),
    ]
