# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('nickname', models.CharField(max_length=20, verbose_name='Nickname')),
                ('posts', models.CharField(default='', max_length=10000, verbose_name='Posts')),
                ('stevens_id', models.CharField(max_length=8, verbose_name='Stevens ID')),
                ('is_Verified', models.BooleanField(default=False, verbose_name='Is verified')),
                ('is_Admin', models.BooleanField(default=False, verbose_name='Is admin')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
        ),
    ]
