# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 03:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_date', models.DateTimeField(auto_created=datetime.datetime(2017, 3, 2, 3, 55, 26, 742160), verbose_name='Expire date')),
                ('active_code', models.CharField(max_length=50, verbose_name='Active Code')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'Active ID',
                'verbose_name_plural': 'Active ID',
            },
        ),
    ]
