# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 04:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useractive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractive',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='useractive',
            name='expire_date',
            field=models.DateTimeField(auto_created=datetime.datetime(2017, 3, 2, 4, 3, 15, 844250), verbose_name='Expire date'),
        ),
    ]
