# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 16:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170301_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractive',
            name='expire_date',
            field=models.DateTimeField(auto_created=datetime.datetime(2017, 3, 3, 16, 17, 56, 363454), verbose_name='Expire date'),
        ),
    ]
