# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 23:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170309_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractive',
            name='is_expired',
            field=models.BooleanField(default=False, verbose_name='Is expired'),
        ),
        migrations.AlterField(
            model_name='useractive',
            name='expire_date',
            field=models.DateTimeField(auto_created=datetime.datetime(2017, 3, 22, 23, 16, 5, 366351), verbose_name='Expire date'),
        ),
    ]
