# Generated by Django 2.1 on 2018-04-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180426_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractive',
            name='expire_date',
            field=models.CharField(auto_created='2018-04-30', max_length=50, verbose_name='Expire date'),
        ),
    ]
