# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Block name')),
                ('desc', models.CharField(max_length=100, verbose_name='Block desc')),
                ('post_nums', models.IntegerField(default=0, verbose_name='Post nums')),
                ('posts', models.CharField(default='0', max_length=1000000, verbose_name='Block posts')),
                ('status', models.IntegerField(choices=[(1, 'exist'), (0, 'deleted')], default=0, verbose_name='Status')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Last Update Timestamp')),
            ],
            options={
                'verbose_name': 'Block name',
                'verbose_name_plural': 'Blocks',
            },
        ),
    ]
