# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_auto_20170303_0430'),
        ('posts', '0013_post_author_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Author Name')),
                ('content', models.CharField(max_length=10000, verbose_name='Content')),
                ('status', models.IntegerField(choices=[(1, 'exist'), (0, 'deleted')], default=1, verbose_name='Status')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Last Update Timestamp')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='Author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post', verbose_name='Post ID')),
            ],
            options={
                'verbose_name_plural': 'Reply',
                'verbose_name': 'Reply',
            },
        ),
    ]
