# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='to_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reply.Reply', verbose_name='Comment Reply'),
        ),
    ]
