# Generated by Django 2.1 on 2018-04-26 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0002_reply_to_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.User', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.Post', verbose_name='Post ID'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='to_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reply.Reply', verbose_name='Comment Reply'),
        ),
    ]
